<?php 
get_header();
get_template_part('inc/index','header');
get_template_part('inc/index','slide-top');
get_template_part('inc/index','about-top');
get_template_part('inc/index','Project-sec');
get_template_part('inc/index','employee');
get_template_part('inc/index','news');
get_footer(); 
?>